### ISSUE TITLE
Monaco editor is not working in Safari 13.1

### ISSUE THREAD

**Issue by jacowley** [microsoft/monaco-editor#2432]
**monaco-editor version:** 0.23.0
**Browser:** Safari 13.1
**OS:** Mac

Upgrading the Monaco editor in our web application from version 0.21.2 to 0.23.0 has stopped our application loading in Safari 13.1. Updating to the latest version of Safari 14.0.3 does fix the issue. However we need to continue to support Safari 13 in the short-term.

We see the following error:

window.matchMedia("(forced-colors: active)").addEventListener is not a function. (In 'window.matchMedia("(forced-colors: active)").addEventListener("change",(function(){e._updateActualTheme()}))', 'window.matchMedia("(forced-colors: active)").addEventListener' is undefined)

This is reproducible on https://microsoft.github.io/monaco-editor/:

![Screenshot 2021-04-09 at 17 02 02](https://user-images.githubusercontent.com/3743958/114209830-fc0ed600-9956-11eb-956e-14028ae59b82.png)

It appears that this is the recent code change that has caused the issue: https://github.com/microsoft/vscode/blob/58faca759ab38b44837c512074fa942f4716a9fa/src/vs/editor/standalone/browser/standaloneThemeServiceImpl.ts#L236

I assume that Safari 13.1 does not implement addEventListener on MediaQueryList, so addListener needs to be used instead.

**Comment by Prinzhorn** [comment]
>  Prior to Safari 14, MediaQueryList is based on EventTarget, so you must use addListener() and removeListener() to observe media query lists. 

https://caniuse.com/?search=addlistener
