### ISSUE TITLE
[Bug] monaco.editor.createDiffNavigator is not a function: undefined

### ISSUE THREAD

**Issue by mwannas-tibco** [microsoft/monaco-editor#4227]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [ ] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Link

https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0#example-creating-the-diffeditor-multi-line-example

### Monaco Editor Playground Code

```typescript
var originalModel = monaco.editor.createModel(
	"This line is removed on the right.\njust some text\nabcd\nefgh\nSome more text",
	"text/plain"
);
var modifiedModel = monaco.editor.createModel(
	"just some text\nabcz\nzzzzefgh\nSome more text.\nThis line is removed on the left.",
	"text/plain"
);

var diffEditor = monaco.editor.createDiffEditor(
	document.getElementById("container"),
	{
		// You can optionally disable the resizing
		enableSplitViewResizing: false,
	}
);


var nav = monaco.editor.createDiffNavigator(diffEditor);
if (nav.canNavigate()) {
	nav.next();
} else {
	diffEditor.revealLine(0);
}
      

diffEditor.setModel({
	original: originalModel,
	modified: modifiedModel,
});
```

### Reproduction Steps

copy and past the code in the monaco editor playground
make sure to select version 0.44.0

### Actual (Problematic) Behavior

Monaco.editor.createDiffNavigator is not a function: undefined

### Expected Behavior

To be able to use monaco.editor.createDiffNavigator 

### Additional Context

bug since 0.44.0
work in <= 0.43.0

**Comment by jairbubbles** [comment]
Looks like it's not available anymore, the sample using this was removed in the playground.

**Comment by jairbubbles** [comment]
I was using it to scroll to first diff. So I took inspiration from https://github.com/microsoft/vscode/blob/8c49a184e1525e19671114680c44171e16d43b09/src/vs/editor/browser/widget/diffEditor/diffEditorWidget.ts#L553
to do it without using the `DiffNavigator`.

Here it is in action in the playground:

https://microsoft.github.io/monaco-editor/playground.html?source=v0.44.0#XQAAAAJ9BAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw6uL3s3g3TZokiQe3t547J-9ebB9cYURQV2C_HyzmFKq-zHr7CL5opGlpi2RAmEsI8D75tN_PKaDXZNPFCC79Yl_xtPH5SUKM1UNdrE-uwHS0QPgNkqyfYlcWUaipOcGvhxnJNccPQ77Le7sRqIvXh39DexbnbKgswSLnICVEtp5zueXn9a-3-v-iDnLkQaIEWsujO56G96N3tA9-z8n6ohaVPUhJx5EIzmA5QJYlRMyb7kV4Jf4pg1pmkv629Z5yh0ZgF6PXtxl45-mCbSOsmANW7UUQO9nlShKKS4SF_cXSn2f3ZbL20WwqPffDJoa8kckt3UefF08m5iubGms5_x4lypiN9lRtmzoYKdf-yKCzWSlhjd0xrn7LViv2WCMPOHRPYSiX85d5mnHy_zZhfMF-8Nbh8zuPR9ANod9wkO6wcKs7GeAYdF6kqldmWJlDHk7tlQDmX7M3_MkfC3eqxDTo1nwYqJmLG0-31uNu25W5dfooeOXejQXobGSBqmgBYMSIJDrsuv__mHj1Mg

@hediet Maybe we can add a sample explaining how to manipulate the line changes ?

**Comment by TianXinCoord** [comment]
Vue3 + Vite5：It's worked bellow

import * as monaco from 'monaco-editor'
import { toRaw } from 'vue'

this.editor = monaco.editor.createDiffEditor(domEditor, xxx

- toRaw(this.editor).goToDiff('previous')
- toRaw(this.editor).goToDiff('next')
