### ISSUE TITLE
ExpandSuggestionDocs Settings conflict with the command panel

### ISSUE THREAD

**Issue by y912765390** [microsoft/monaco-editor#2241]
In the past, I made the details expand by default in this way, but in the current version this configuration makes the command panel unusable   
```js
this.editor = window.monaco.editor.create(this.$el, this.editorOptions, {
        storageService: {
          get() {},
          remove() {},
          getBoolean(key) {
            if (window.activeLanguage && window.activeLanguage == 'java' && key === 'expandSuggestionDocs') {
              return true;
            }
            return false;
          },
          store() {},
          onWillSaveState() {},
          onDidChangeStorage() {}
        }
      }
);
```

**Comment by alexdima** [comment]
This works for me:
```
monaco.editor.create(document.getElementById("container"), {
    value: "function hello() {\n\talert('Hello world!');\n}",
    language: "javascript"
}, {
    storageService: {
        get() { },
        remove() { },
        getBoolean(key) {
            return true;
        },
        store() { },
        onWillSaveState() { },
        onDidChangeStorage() { }
    }
});
```

So it looks like you have a problem with `window.activeLanguage`

**Comment by y912765390** [comment]
What do you mean? I'm making this change so that the right-click Command Pelette F11 is not available. Now, how do I get my Documention of CompletionItemProvide expanded by default if I don't do that

**Comment by alexdima** [comment]
@y912765390 

The snippet I have posted above makes it that the suggestion details are expanded by default:

![image](https://user-images.githubusercontent.com/5047891/103288450-2dd1e180-49e5-11eb-94f9-4a53bba75d7f.png)

**Comment by y912765390** [comment]
Yes  .I know.  But if I do this . F1  Command  Palette  will  not  show  。 Try F1 with your change. The same result

**Comment by charrondev** [comment]
The example from @alexdima works, but as I understand this should come with some drawbacks. Is there a way to just configure this to be always open without configuring anything else?

**Comment by y912765390** [comment]
> @alexdima中的示例有效，但是据我了解，这应该有一些缺点。有没有一种方法可以将其配置为始终打开而不配置其他任何内容？

I know this is fine but it will make the F1 command panel unusable

**Comment by alexdima** [comment]
The error in the console is revealing:
```
VM17 editor.main.js:2248 TypeError: this.storageService.getNumber is not a function
```

So:
```
monaco.editor.create(document.getElementById("container"), {
    value: "function hello() {\n\talert('Hello world!');\n}",
    language: "javascript"
}, {
    storageService: {
        get() { },
        remove() { },
        getBoolean(key) {
            return true;
        },
        getNumber(key) {
            return 0;
        },
        store() { },
        onWillSaveState() { },
        onDidChangeStorage() { }
    }
});
```

**Comment by martonlanga** [comment]
Thanks @alexdima this works. I was missing `remove()`.

From Stackoverflow:

> The storage service is also used for things like remembering most recently used suggestions (to personalize IntelliSense) etc., so if you need that functionality you may want to implement the other functions as well

I didn't notice any difference in functionality for now. Are there any important features one would miss out on by leaving `storageService` unimplemented?

**Comment by y912765390** [comment]
thank you ver much!The problem was solved

**Comment by alexdima** [comment]
@martonlanga Sorry, I cannot answer that because I don't know. You can try searching for `IStorageService` in the `src/vs/editor` folder in the `vscode` repo and see which features use that.

**Comment by anvaka** [comment]
This is a hack, don't use it for production, but you can get this to work in `0.31.1` this way:

```js
  let editor = monaco.editor.create(container, {value: your_code});
  let {widget} = editor.getContribution('editor.contrib.suggestController');
  if (widget) {
    const suggestWidget = widget.value;
    if (suggestWidget && suggestWidget._setDetailsVisible) {
      // This will default to visible details. But when user switches it off
      // they will remain switched off:
      suggestWidget._setDetailsVisible(true);
    }
    // I also wanted my widget to be shorter by default:
    if (suggestWidget && suggestWidget._persistedSize) {
      suggestWidget._persistedSize.store({width: 200, height: 256});
    }
  }
  ```

**Comment by liuyike98** [comment]
> 

well done! your code works, and others' above not work any more

**Comment by pawansingh00** [comment]
@anvaka Is there any way to Resize the Right side part to ?
