### ISSUE TITLE
colorize and colorizeElement methods throw an error with embedded languages

### ISSUE THREAD

**Issue by mofojed** [microsoft/monaco-editor#1649]
**monaco-editor version:** 0.18.1
**Browser:** Chrome 78.0.3904.70
**OS:** macOS Catalina

**Steps or JS usage snippet reproducing the issue:**
Mentioned in this stackoverflow: https://stackoverflow.com/questions/58246978/monaco-editor-colorize-throw-an-exception-when-html-includes-script-tag
Demonstrated in this Fiddle: https://jsfiddle.net/tndefzsu/

It would appear the colorize/colorizeElement methods no longer work, returning an error such as:
```
TypeError: this._embeddedModes.hasOwnProperty is not a function
    at MonarchTokenizer.getLoadStatus (monarchLexer.js:426)
    at execute (colorizer.js:149)
    at colorizer.js:160
    at new Promise (<anonymous>)
    at _colorize (colorizer.js:144)
    at Function.Colorizer.colorize (colorizer.js:64)
    at Function.Colorizer.colorizeElement (colorizer.js:36)
```

This used to be working fine in 0.17, and appears to be a new issue with 0.18.1

This seems to be an issue with languages that contain embedded languages (like html).

**Comment by mofojed** [comment]
Digging into the code a bit, I think this `if` check can just be removed: https://github.com/microsoft/vscode/blob/master/src/vs/editor/standalone/common/monarch/monarchLexer.ts#L424
The type is aliased in the definition: https://github.com/microsoft/vscode/blob/master/src/vs/editor/standalone/common/monarch/monarchLexer.ts#L383, and doesn't need to check hasOwnProperty.

Issue was introduced with this change: https://github.com/microsoft/vscode/commit/bb384a83e586dda0e42227d55813c7ce744fc99b

**Comment by mofojed** [comment]
Issue already described here: https://github.com/microsoft/vscode/issues/84394
Fixed with https://github.com/microsoft/vscode/commit/38ac339e7aa481b0f618eb8edb7948954ddf6277

**Comment by mofojed** [comment]
Given that the fix is checked in to vscode, is there any visibility on when this fix will propagate to monaco-editor?

**Comment by alexdima** [comment]
The fix will come out with the next monaco editor release.

**Comment by mofojed** [comment]
Thanks, is there a timeline for the next editor release?

**Comment by mofojed** [comment]
Looks like 0.19.0 was release which resolves this issue: https://github.com/microsoft/monaco-editor/blob/master/CHANGELOG.md
