### ISSUE TITLE
[Bug] TypeError after upgrading from 0.31.1 to any newer version

### ISSUE THREAD

**Issue by mad42** [microsoft/monaco-editor#3027]
### Reproducible in vscode.dev or in VS Code Desktop?

- [X] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [X] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Actual Behavior

`TypeError: window.matchMedia(n).addEventListener is not a function. (In 'window.matchMedia(n).addEventListener("change",e)', 'window.matchMedia(n).addEventListener' is undefined)`

### Additional Context

build with esbuild 0.14.27

the error occurs when creating the editor:

```js
      emmetMonaco.emmetHTML(monaco);

      let editor_html = monaco.editor.create(element, {
        language: "html",
        tabSize: 2,
        fontSize: 12,
        insertSpaces: false,
        formatOnType: true,
        automaticLayout: true,
        minimap: { enabled: false },
        hover: { enabled: false },
        theme: "vs-dark",
      });

      editor_html.addCommand(
        monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyS,
        function () {
          get_code_callback("html", editor_html.getValue());
        }
      );
```

was working properly on 0.31.1

**Comment by mad42** [comment]
fails with a minimal situation too

```js
monaco.editor.create(element);
```

**Comment by hediet** [comment]
This looks like you are using an unsupported browser.

I cannot reproduce your issue in the playground.

**Comment by mad42** [comment]
Couldn't find any poly-fill handle that, could you point me in the right direction ?
