### ISSUE TITLE
"ReferenceWidget depends on UNKNOWN service IPeekViewService" error since 0.17

### ISSUE THREAD

**Issue by ulrichb** [microsoft/monaco-editor#1464]
**monaco-editor version:** 0.17.1
**Browser:** Chrome / Firefox
**OS:** Win

**Steps or JS usage snippet reproducing the issue:**

Just open the [Monaco Editor playground](https://microsoft.github.io/monaco-editor/playground.html) and hit Shift+F12 or Alt+F12 on a symbol.

*Error in the browser console:*
![image](https://user-images.githubusercontent.com/388796/58736943-f31a5880-83ff-11e9-95ff-877f21145283.png)
<details><summary>as text</summary>
<p>

```plain
simpleServices.js:206 Error: [createInstance] ReferenceWidget depends on UNKNOWN service IPeekViewService.
    at InstantiationService._createInstance (instantiationService.js:144)
    at InstantiationService.createInstance (instantiationService.js:118)
    at StandaloneReferencesController.ReferencesController.toggleWidget (referencesController.js:248)
    at ReferenceAction.run (referenceSearch.js:140)
    at ReferenceAction.EditorAction.runEditorCommand (editorExtensions.js:230)
    at editorExtensions.js:187
    at InstantiationService.invokeFunction (instantiationService.js:94)
    at StandaloneEditor.CodeEditorWidget.invokeWithinContext (codeEditorWidget.js:298)
    at ReferenceAction.EditorCommand.runCommand (editorExtensions.js:179)
    at handler (editorExtensions.js:101)
    at InstantiationService.invokeFunction (instantiationService.js:94)
    at StandaloneCommandService.executeCommand (simpleServices.js:260)
    at StandaloneKeybindingService.AbstractKeybindingService._doDispatch (abstractKeybindingService.js:195)
    at StandaloneKeybindingService.AbstractKeybindingService._dispatch (abstractKeybindingService.js:142)
    at HTMLDivElement.<anonymous> (simpleServices.js:287)
```

</p>
</details>

Both worked in Monaco Editor 0.16.2.

**Comment by AviVahl** [comment]
we experienced the same in our project, when upgrading to latest `monaco-editor-core`.
it appears the registry in `monaco-editor-core/esm/vs/platform/instantiation/common/extensions.js` is not being exported or registered to the `InstantiationService`.
In `vscode`, `workbench.ts` calls `getServices()` and registers them (in `initServices()`).

**Comment by ulrichb** [comment]
@mjbvz Could you maybe have a look at this? (Still broken in 0.17.1)

**Comment by ulrichb** [comment]
@AviVahl Thanks for info. Do you have any workaround?

**Comment by AviVahl** [comment]
We are using 0.16 until issue is resolved. No workaround from our end, as the service registration/initialization flow is quite complex.

**Comment by ulrichb** [comment]
Nice. Many, many thanks @jrieken !

**Comment by AviVahl** [comment]
Awesome. Thanks for the fix. Any chance for a patch release of `monaco-editor`/`monaco-editor-core`? :)

**Comment by ulrichb** [comment]
Pleeease release a new version containing the fix.

![purr](https://i.giphy.com/media/d1Ag5mYrW9Aek/giphy.webp)
