### ISSUE TITLE
[Bug] [0.55.0-dev-20251024] types for monaco.languages.json.* don't exist

### ISSUE THREAD

**Issue by AviVahl** [microsoft/monaco-editor#5075]
### Reproducible in vscode.dev or in VS Code Desktop?

- [x] Not reproducible in [vscode.dev](https://vscode.dev) or VS Code Desktop

### Reproducible in the monaco editor playground?

- [x] Not reproducible in [the monaco editor playground](https://microsoft.github.io/monaco-editor/playground.html)

### Monaco Editor Playground Code

```typescript

```

### Reproduction Steps

```sh
mkdir monaco-json-types
cd monaco-json-types
npm init -y
npm i typescript monaco-editor@0.55.0-dev-20251024
npx tsc --init
npm pkg set type=module
echo "import * as monaco from 'monaco-editor'; monaco.languages.json.jsonDefaults.setDiagnosticsOptions({});" > main.ts
npx tsc --noEmit
```

### Actual (Problematic) Behavior

```
main.ts:1:59 - error TS2339: Property 'json' does not exist on type 'typeof languages'.

1 import * as monaco from 'monaco-editor'; monaco.languages.json.jsonDefaults.setDiagnosticsOptions({});
                                                            ~~~~


Found 1 error in main.ts:1
```

### Expected Behavior

No type errors.

### Additional Context

Works with 0.54.0

**Comment by AviVahl** [comment]
FYI @hediet 
would be nice if the next version won't have this issue.
0.53.0 had https://github.com/microsoft/monaco-editor/issues/4981
0.54.0 had https://github.com/microsoft/monaco-editor/issues/5025
and now 0.55.0-dev has this issue.

Every time I wait a whole month to get a fixed version... just to get hit with another issue.

Appreciate the work. Would love to be able to use it.

**Comment by hediet** [comment]
This is going to be a breaking change in the next stable release.
`monaco.languages.*` moved to `monaco.*`.

This is because there is no non-hacky way for the monaco-editor package to add elements to namespaces exported by moaco-editor-core (here `languages`).

**Comment by AviVahl** [comment]
@hediet I've noticed 0.55.0-rc regressed and no longer has `monaco.json.*`

**Comment by hediet** [comment]
Thanks for the heads up! [The problems was that the typings used `editor.api.d.ts`, not `editor.main.d.ts`.](https://github.com/microsoft/monaco-editor/issues/5123) The fix will be included in v0.55.1, which I hope to ship today.
